version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - justingrote
  ignore:
  - dependency-name: Blazorise.Components
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.DataGrid
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.Bootstrap
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.Icons.FontAwesome
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Microsoft.AspNetCore.Components.WebAssembly.DevServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Components.WebAssembly
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
